services:
 
  server:
    build: .
    stop_grace_period: 30s
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    env_file: .env
    networks:
      - backend

  postgres:
    image: postgres:17
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:7-alpine
    command: redis-server --notify-keyspace-events Ex
    volumes:
      - redis_data:/data
    networks:
      - backend

volumes:
  postgres_data:
  redis_data:

networks:
  backend:
    driver: bridge
